apiVersion: apps/v1
kind: Deployment
metadata:
  name: messayed-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mesayed-springboot
  template:
    metadata:
      labels:
        app: messayed-springboot
    spec:
      containers:
        - name: springboot
          image: messayed/messayed-devops-capstone:messayed-devops-capstone
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: messayed-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: messayed-springboot
